# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shoeshop-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: shoeshop.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shoeshop-service
            port:
              number: 80
